class Cell{
    constructor(i_,j_){
        this.i=i_;
        this.j=j_;
        this.size=40;
        this.x=this.j*this.size;
        this.y=this.i*this.size;
        this.top=true;
        this.right=true;
        this.left=true;
        this.bottom=true;
        this.visited=false;
    }
    show(){
        stroke(255);
        noFill();
        if(this.top){
            line(this.x,this.y,this.x+this.size,this.y);
        }
        if(this.right){
            line(this.x+this.size,this.y,this.x+this.size,this.y+this.size);
        }
        if(this.left){
            line(this.x,this.y,this.x,this.y+this.size);
        }
        if(this.bottom){
            line(this.x,this.y+this.size,this.x+this.size,this.y+this.size);
        }
    }
}